### ISSUE TITLE
Use Path instead of os

### ISSUE THREAD

**Issue by satoon101** [Warcraft-GO-Team/Warcraft-GO#4]
Not a huge deal, but I find using path.Path much simpler than using os directly.  This is the change I would propose (in [this](https://github.com/Warcraft-GO-Team/Warcraft-GO/blob/master/addons/source-python/plugins/wcgo/configs.py#L84) line):
```python
database_path = Path(__file__).parent / 'wcgo.db'
```
Obviously with the following import
```python
from path import Path
```

Though, since a database is technically 'data', I would recommend instead using the following:
```python
from paths import PLUGIN_DATA_PATH

database = PLUGIN_DATA_PATH / 'wcgo.db'
```

I would have made a pull request, but I am not sure which of the two options you would prefer.

**Comment by Mahi** [comment]
I believe we should be using the data path since that's what you guys designed it for, even if it's just one file.

I also believe the path doesn't need to be configurable, so if you'd rather make a pull request, make sure to change the database path to be used directly in `wcgo.py` instead of being in the `configs.py`, especially now that we're intending to move to different configuration formats.

**Comment by Mahi** [comment]
I actually updated this already in https://github.com/Warcraft-GO-Team/Warcraft-GO/commit/7232746dc7b1100802fa1a2218b36250a4f0c48e

Thanks again for the suggestion!
